apiVersion: v1
kind: Service
metadata:
    name: commandsnpservice-srv
spec:
  type: NodePort
  selector:
    app: commandservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30003
